version: '3'

services:
  dev:
    container_name: warwick
    image: warwick:1.0.0
    networks:
      massbit:
        ipv4_address: "34.80.254.101"
    build:
      dockerfile: Dockerfile.dev
      context: .
      target: development
    command: npm run start:local
    ports: 
    - "3002:3000"
    environment:
      - REQUEST_SCHEME=https
      - DB_HOST=host.docker.internal
      - DB_MONITOR_HOST=host.docker.internal
      - REDIS_HOST=host.docker.internal
    volumes:
      - .:/app
      - /app/node_modules
      - ./config/tasks.yaml:/massbit/massbitroute/app/src/services/tasks.yaml
      - ./config/shareConfigs.yaml:/massbit/massbitroute/app/src/services/shareConfigs.yaml
      - ./config/blockchainConfigs.yaml:/massbit/massbitroute/app/src/services/blockchainConfigs.yaml
    extra_hosts:
    - "host.docker.internal:host-gateway"
    restart: unless-stopped

networks:
  massbit:
    external:
      name: "massbit"
