dot-mainnet:
  chainId: Polkadot
  maxBlockLate: 10
# ethereum
eth-mainnet:
  chainId: 1
  maxBlockLate: 10
eth-goerli:
  chainId: 5
  maxBlockLate: 10
eth-sepolia:
  chainId: 11155111
  maxBlockLate: 10
# bsc
bsc-mainnet:
  chainId: 56
  maxBlockLate: 10
bsc-testnet:
  chainId: 97
  maxBlockLate: 10
# matic
matic-mainnet:
  chainId: 137
  maxBlockLate: 10
matic-mumbai:
  chainId: 80001
  maxBlockLate: 10
