gwRtt:
  http:
  - name: rtt
    timeout: 3000
    url: "{{scheme}}://{{ip}}/_rtt"
    method: GET
    attemptNumber: 3
    headers:
      Host: internal.massbitroute.net
  - name: check-gateway
    timeout: 3000
    url: "{{scheme}}://{{ip}}/config/gw-check"
    method: POST
    attemptNumber: 1
    headers:
      Host: internal.massbitroute.net
      Authorization: "{{#build_jwt appKey id}}{{/build_jwt}}"
  validates:
  - each:
      rules: ["http", "http-success"]
      http: rtt
      successPercent: 50
    allFail:
      rules: ["change-status-reported"]
      reason: check nginx fail
  - each:
      rules: ["http", "http-success"]
      http: check-gateway
      successPercent: 100
    allFail:
      rules: ["change-status-reported"]
      reason: check so-zesty-jr fail
    allSuccess:
      rules: ["change-status-running"]
      reason: ok
dotLatestBlock:
  blockchains: ["dot"]
  type: rpc
  http:
  - name: check-chainid
    timeout: 5000
    url: "{{dataSource}}"
    method: POST
    attemptNumber: 1
    headers:
      "content-type": application/json
      "X-Api-Key": "{{appKey}}"
    body:
      jsonrpc: "2.0"
      method: "system_chain"
      params: []
      id: 1
  - name: check-block
    timeout: 5000
    url: "{{dataSource}}"
    method: POST
    attemptNumber: 1
    headers:
      "content-type": application/json
      "X-Api-Key": "{{appKey}}"
    body:
      jsonrpc: "2.0"
      method: "chain_getBlock"
      params: []
      id: 1
  validates:
  - each:
      rules: ["http", "http-success", "map-response-field", "check-chain-id"]
      http: check-chainid
      mapFields:
        - name: chainId
          field: "result"
      successPercent: 100
    allFail:
      rules: ["change-status-reported"]
      reason: check chainId fail, chainId={{context.chainId}}
  - each:
      rules: ["http", "http-success", "map-response-field"]
      http: check-block
      mapFields:
        - name: "blockNumber-{{blockchain}}-{{network}}"
          from: 1
          operator: parse-hex
          field: "result.block.header.number"
      successPercent: 100
    allFail:
      rules: ["change-status-reported"]
      reason: get latestBlock fail
    allSuccess:
      rules: ["reduce"]
      mapShareFields:
        - name: "maxBlock-{{blockchain}}-{{network}}"
          operator: max
          field: "blockNumber-{{blockchain}}-{{network}}"
  - each:
      rules: ["check-block-late"]
    allFail:
      rules: ["change-status-reported"]
      reason: current block is late
    allSuccess:
      rules: ["change-status-running"]
      reason: ok
ethLatestBlock:
  blockchains: ["eth", "bsc"]
  type: rpc
  http:
  - name: check-chainid
    timeout: 5000
    url: "{{dataSource}}"
    method: POST
    attemptNumber: 1
    headers:
      "content-type": application/json
      # "X-Api-Key": "{{appKey}}"
    body:
      jsonrpc: "2.0"
      method: "eth_chainId"
      params: []
      id: 1
  - name: check-block
    timeout: 5000
    url: "{{dataSource}}"
    method: POST
    attemptNumber: 1
    headers:
      "content-type": application/json
      # "X-Api-Key": "{{appKey}}"
    body:
      jsonrpc: "2.0"
      method: "eth_getBlockByNumber"
      params: ["latest", true]
      id: 1
  validates:
  - each:
      rules: ["http", "http-success", "map-response-field", "check-chain-id"]
      http: check-chainid
      mapFields:
        - name: chainId
          operator: parse-hex
          field: "result"
      successPercent: 100
    allFail:
      rules: ["change-status-reported"]
      reason: check chainId fail, chainId={{context.chainId}}
  - each:
      rules: ["http", "http-success", "map-response-field"]
      http: check-block
      mapFields:
        - name: "blockNumber-{{blockchain}}-{{network}}"
          from: 1
          operator: parse-hex
          field: "result.number"
      successPercent: 100
    allFail:
      rules: ["change-status-reported"]
      reason: get latestBlock fail
    allSuccess:
      rules: ["reduce"]
      mapShareFields:
        - name: "maxBlock-{{blockchain}}-{{network}}"
          operator: max
          field: "blockNumber-{{blockchain}}-{{network}}"
  - each:
      rules: ["check-block-late"]
    allFail:
      rules: ["change-status-reported"]
      reason: current block is late
    allSuccess:
      rules: ["change-status-running"]
      reason: ok
