- name: rtt
  cronTime: "*/10 * * * * *"
  config:
    useConfig: ["gwRtt"]
    datasource: running-gateway
    validates:
    - each:
        rules: ["http", "http-success"]
        http: rtt
        successPercent: 50
      allFail:
        rules: ["change-status-investigate", "schedule"]
        reason: check nginx fail
        reasonCode: GW_ERR_NGINX
        schedule:
          name: rtt-last-hit
          useConfig: ["gwRtt"]
          timer: 3600
    - each:
        rules: ["http", "http-success"]
        http: check-gateway
        successPercent: 100
      allFail:
        rules: ["change-status-investigate", "schedule"]
        reason: check so-zesty-jr fail
        reasonCode: GW_ERR_ZESTY_JR
        schedule:
          name: rtt-last-hit
          useConfig: ["gwRtt"]
          timer: 3600
      allSuccess:
        rules: ["remove-from-scheduler"]
        schedule:
          name: rtt-last-hit
- name: rtt-investigate
  cronTime: "0 */5 * * * *"
  config:
    useConfig: ["gwRtt"]
    datasource: investigate-gateway
    validates:
    - each:
        rules: ["http", "http-success"]
        http: rtt
        successPercent: 50
      allFail:
        rules: ["schedule-if-not-exist"]
        schedule:
          name: rtt-last-hit
          useConfig: ["gwRtt"]
          timer: 3600
    - each:
        rules: ["http", "http-success"]
        http: check-gateway
        successPercent: 100
      allFail:
        rules: ["schedule-if-not-exist"]
        schedule:
          name: rtt-last-hit
          useConfig: ["gwRtt"]
          timer: 3600
      allSuccess:
        rules: ["change-status-running", "remove-from-scheduler"]
        reason: ok
        reasonCode: SUCCESS
        schedule:
          name: rtt-last-hit
# Polkadot nodes
- name: latest-block
  cronTime: "0 */1 * * * *"
  config:
    useConfig: ["dotLatestBlock"]
    datasource: running-node
    validates:
    - each:
        rules: ["http", "http-success"]
        http: check-chainid
        successPercent: 100
      allFail:
        rules: ["change-status-investigate", "schedule"]
        reason: "check chainId fail, error: http"
        reasonCode: NODE_ERR_CHAINID
        schedule:
          name: latest-block-last-hit
          withDatasource: running-node
          useConfig: ["dotLatestBlock"]
          timer: 600
    - each:
        rules: ["map-response-field", "check-chain-id"]
        mapFields:
          - name: chainId
            field: "result"
      allFail:
        rules: ["change-status-reported"]
        reason: check chainId fail, chainId={{context.chainId}}
        reasonCode: NODE_ERR_CHAINID
    - each:
        rules: ["http", "http-success", "map-response-field"]
        http: check-block
        mapFields:
          - name: "blockNumber-{{blockchain}}-{{network}}"
            from: 1
            operator: parse-hex
            field: "result.block.header.number"
        successPercent: 100
      allFail:
        rules: ["change-status-investigate", "schedule"]
        reason: get latestBlock fail
        reasonCode: NODE_ERR_LATESTBLOCK
        schedule:
          name: latest-block-last-hit
          withDatasource: running-node
          useConfig: ["dotLatestBlock"]
          timer: 3600
      allSuccess:
        rules: ["reduce"]
        mapShareFields:
          - name: "maxBlock-{{blockchain}}-{{network}}"
            operator: max
            field: "blockNumber-{{blockchain}}-{{network}}"
    - each:
        rules: ["check-block-late"]
      allFail:
        rules: ["change-status-investigate", "schedule"]
        reason: current block is late
        reasonCode: NODE_ERR_LATESTBLOCK
        schedule:
          name: latest-block-last-hit
          withDatasource: running-node
          useConfig: ["dotLatestBlock"]
          timer: 3600

- name: latest-block-investigate
  cronTime: "0 */5 * * * *"
  config:
    useConfig: ["dotLatestBlock"]
    datasource: investigate-node
    validates:
    - each:
        rules: ["http", "http-success"]
        http: check-chainid
        successPercent: 100
      allFail:
        rules: ["schedule-if-not-exist"]
        schedule:
          name: latest-block-last-hit
          withDatasource: running-node
          useConfig: ["dotLatestBlock"]
          timer: 600
    - each:
        rules: ["map-response-field", "check-chain-id"]
        mapFields:
          - name: chainId
            field: "result"
      allFail:
        rules: ["change-status-reported"]
        reason: check chainId fail, chainId={{context.chainId}}
        reasonCode: NODE_ERR_CHAINID
    - each:
        rules: ["http", "http-success", "map-response-field"]
        http: check-block
        mapFields:
          - name: "blockNumber-{{blockchain}}-{{network}}"
            from: 1
            operator: parse-hex
            field: "result.block.header.number"
        successPercent: 100
      allSuccess:
        rules: ["reduce"]
        mapShareFields:
          - name: "maxBlock-{{blockchain}}-{{network}}"
            operator: max
            field: "blockNumber-{{blockchain}}-{{network}}"
    - each:
        rules: ["check-block-late"]
      allFail:
        rules: ["schedule-if-not-exist"]
        schedule:
          name: latest-block-last-hit
          withDatasource: running-node
          useConfig: ["dotLatestBlock"]
          timer: 3600
      allSuccess:
        rules: ["change-status-running", "remove-from-scheduler"]
        reason: ok
        reasonCode: SUCCESS
        schedule:
          name: latest-block-last-hit

# Ethereum nodes
- name: latest-block
  cronTime: "0 */1 * * * *"
  config:
    useConfig: ["ethLatestBlock"]
    datasource: running-node
    validates:
    - each:
        rules: ["http", "http-success"]
        http: check-chainid
        successPercent: 100
      allFail:
        rules: ["change-status-investigate", "schedule"]
        reason: "check chainId fail, error: http"
        reasonCode: NODE_ERR_CHAINID
        schedule:
          name: latest-block-last-hit
          withDatasource: running-node
          useConfig: ["ethLatestBlock"]
          timer: 600
    - each:
        rules: ["map-response-field", "check-chain-id"]
        mapFields:
          - name: chainId
            operator: parse-hex
            field: "result"
      allFail:
        rules: ["change-status-reported"]
        reason: check chainId fail, chainId={{context.chainId}}
        reasonCode: NODE_ERR_CHAINID
    - each:
        rules: ["http", "http-success", "map-response-field"]
        http: check-block
        mapFields:
          - name: "blockNumber-{{blockchain}}-{{network}}"
            from: 1
            operator: parse-hex
            field: "result.number"
        successPercent: 100
      allFail:
        rules: ["change-status-investigate", "schedule"]
        reason: get latestBlock fail
        reasonCode: NODE_ERR_LATESTBLOCK
        schedule:
          name: latest-block-last-hit
          withDatasource: running-node
          useConfig: ["ethLatestBlock"]
          timer: 3600
      allSuccess:
        rules: ["reduce"]
        mapShareFields:
          - name: "maxBlock-{{blockchain}}-{{network}}"
            operator: max
            field: "blockNumber-{{blockchain}}-{{network}}"
    - each:
        rules: ["check-block-late"]
      allFail:
        rules: ["change-status-investigate", "schedule"]
        reason: current block is late
        reasonCode: NODE_ERR_LATESTBLOCK
        schedule:
          name: latest-block-last-hit
          withDatasource: running-node
          useConfig: ["ethLatestBlock"]
          timer: 3600

- name: latest-block-investigate
  cronTime: "0 */5 * * * *"
  config:
    useConfig: ["ethLatestBlock"]
    datasource: investigate-node
    validates:
    - each:
        rules: ["http", "http-success"]
        http: check-chainid
        successPercent: 100
      allFail:
        rules: ["schedule-if-not-exist"]
        schedule:
          name: latest-block-last-hit
          withDatasource: running-node
          useConfig: ["ethLatestBlock"]
          timer: 600
    - each:
        rules: ["map-response-field", "check-chain-id"]
        mapFields:
          - name: chainId
            operator: parse-hex
            field: "result"
      allFail:
        rules: ["change-status-reported"]
        reason: check chainId fail, chainId={{context.chainId}}
        reasonCode: NODE_ERR_CHAINID
    - each:
        rules: ["http", "http-success", "map-response-field"]
        http: check-block
        mapFields:
          - name: "blockNumber-{{blockchain}}-{{network}}"
            from: 1
            operator: parse-hex
            field: "result.number"
        successPercent: 100
      allSuccess:
        rules: ["reduce"]
        mapShareFields:
          - name: "maxBlock-{{blockchain}}-{{network}}"
            operator: max
            field: "blockNumber-{{blockchain}}-{{network}}"
    - each:
        rules: ["check-block-late"]
      allFail:
        rules: ["schedule-if-not-exist"]
        schedule:
          name: latest-block-last-hit
          withDatasource: running-node
          useConfig: ["ethLatestBlock"]
          timer: 3600
      allSuccess:
        rules: ["change-status-running", "remove-from-scheduler"]
        reason: ok
        reasonCode: SUCCESS
        schedule:
          name: latest-block-last-hit
